title: WA4OSH Consulting
email: kr@wa4osh.com
description: >- # this means to ignore newlines until "baseurl:"
  Konrad Roeder's consulting in Python test automation, systems engineering, and HAM radio projects. Explore my work on LoRa APRS, patents and my upcoming book on AI-driven testing.
baseurl: "" # the subpath of your site
url: "https://WA4OSH.com" # the base hostname & protocol for your site
twitter_username: wa4osh
github_username: wa4osh

# Build settings
theme: minima
plugins:
  - jekyll-feed